apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-stack
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: helm-stack
  source:
    path: kube-prometheus-stack
    repoURL: https://github.com/ArunBrainScale/Prometheus-stack.git
    targetRevision: HEAD
    helm:
      values: |
        prometheus:
          ingress:
            enabled: true
            annotations: {kubernetes.io/ingress.class: "nginx"}
            hosts: ["prometheus.example.com"]
            paths: ["/prom"]
      version: v3
  destination:
    namespace: prometheus-stack
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
